# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create([{ name: "Rob B.", email: "robb@email.com", phone: "(416) 327-3682", title: "Assistant Deputy Minister Chief Administrative Officer", adm_office: true, adm: true, password: "123456" },
  { name: 'Judi P.', email: "jp@email.com", phone: "(416) 326-7039", title: "Executive Assistant", adm_office: true, staff: true, password: "123456" },
  { name: "Conn Car", email: "cc@email.com", phone: "(416) 325-6866", title: "Admin. Assistant", adm_office: true, staff: true, password: "123456" },
  { name: "Nat R.", email: "natr@email.com", phone: "(416) 212-4215", title: "Events & Communications Coordinator", adm_office: true, staff: true, password: "123456" },
  { name: "Nad Alj", email: "nad.alj@emailcom", phone: "(416) 906-5018", title: "Project Officer", adm_office: true, staff: true, password: "123456" },
  { name: "Cat Gui", email: "cg@email.com", phone: "(416) 325-6828", title: "French Language Coordinator", adm_office: true, staff: true, password: "123456" },
  { name: "Iso Kuzm", email: "isku@email.com", phone: "(416) 325-9366", title: "Exec. Lead, Transfer Payment Information", adm_office: true, staff: true, password: "123456" },
  # HR
  { name: "Christi C.", email: "chrc@email.com", phone: "(416) 325-6599", title: "Director", strategic_human_resources: true, director: true, password: "123456" },
  { name: "Mich J.", email: "michj@email.com", phone: "(416) 325-6608", title: "Admin. Assistant", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Anne Azz.", email: "anna@email.com", phone: "(416) 314-3823", title: "Manager (A)", strategic_human_resources: true, manager: true, password: "123456" },
  { name: "Nav Na.", email: "nn@email.com", phone: "(416) 326-2990", title: "Manager (A)", strategic_human_resources: true, manager: true, password: "123456" },
  { name: "Van P.", email: "vp@email.com", phone: "(416) 325-9943", title: "HR Projects Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Rac F.", email: "rf@email.com", phone: "(416) 325-7598", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Ji D.", email: "jd@email.com", phone: "(416) 325-3624", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Gab Cam.", email: "gbc@email.com", phone: "(416) 212-4872", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Yv Ch.", email: "yc@email.com", phone: "(416) 325-6873", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Di Bri.", email: "db@email.com", phone: "(416) 212-3170", title: "Workforce Planner", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "Se Des.", email: "sd@email.com", phone: "(416) 325-7362", title: "Project Coordinator", strategic_human_resources: true, staff: true, password: "123456" },
  { name: "X Na.", email: "xn@email.com", phone: "(416) 326-7234", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "123456" },
  #SMF
  { name: "Nel J.", email: "nj@email.com", phone: "(416) 314-3309", title: "Director", service_management_and_facilities: true, director: true, password: "123456" },
  { name: "Sur Dur.", email: "srdr@email.com", phone: "(416) 326-8381", title: "Financial and Admin. Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "P Res.", email: "pre@email.com", phone: "(416) 326-5826", title: "Emergency Management Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Jo Lare.", email: "jolo@email.com", phone: "(416) 212-6984", title: "Business Analyst", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Gi Co.", email: "gico@email.com", phone: "(416) 327-4818", title: "Emergency Management Assistant", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Al Be.", email: "alb@email.com", phone: "(416) 325-8776", title: "Manager, FOI, Privacy and Information Management", service_management_and_facilities: true, manager: true, password: "123456" },
  { name: "P Ca.", email: "pc@email.com", phone: "(416) 326-1344", title: "Tougas FOI Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Dal Bou.", email: "db@email.com", phone: "(416) 325-8899", title: "FOI Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Mi N.", email: "min@email.com", phone: "(416) 325-6156", title: "FOI and Information Management Analyst", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Pa El", email: "pe@email.com", phone: "(416) 212-0176", title: "Advisor, IM and Access Strategy (A)", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Jay T.", email: "jt@email.com", phone: "(416) 327-4824", title: "Freedom of Information Program Assistant (A)", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "C Pe.", email: "cp@email.com", phone: "(416) 325-6423", title: "Manager, Facilities and Service Management", service_management_and_facilities: true, manager: true, password: "123456" },
  { name: "M Z.", email: "mz@email.com", phone: "(416) 325-6451", title: "Facilities Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "L Lo.", email: "ll@email.com", phone: "(416) 326-8384", title: "Facilities Coordinator/ Business Analyst", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Ma A.", email: "ma@email.com", phone: "(416) 325-6467", title: "Security Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Rob C.", email: "rc@email.com", phone: "(416) 326-1762", title: "Security Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Ha T.", email: "ht@email.com", phone: "(416) 325-6570", title: "Business Analyst", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "K Tan.", email: "kt@email.com", phone: "(416) 212-0468", title: "Manager, OITC", service_management_and_facilities: true, manager: true, password: "123456" },
  { name: "Be V.", email: "bv@email.com", phone: "(416) 212-0465", title: "Client Relations Coordinator", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Mike N.", email: "miken.@email.com", phone: "(416) 212-0456", title: "Information Services Officer", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Ca Co.", email: "caco@email.com", phone: "(416) 313-3400", title: "Client Relations Assistant", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Am B.", email: "amb@email.com", phone: "(416) 313-3400", title: "Client Relations Assistant", service_management_and_facilities: true, staff: true, password: "123456" },
  { name: "Ra Ra.", email: "rr@email.com", phone: "(416) 313-3400", title: "Client Relations Representative", service_management_and_facilities: true, staff: true, password: "123456" },
  #BPF
  { name: "Kat R.", email: "ktr@email.com", phone: "(416) 325-1137", title: "Director", business_planning_and_finance: true, director: true, password: "123456" },
  { name: "K J.", email: "kj@email.com", phone: "(416) 320-0832", title: "Associate Director", business_planning_and_finance: true, manager: true, password: "123456" },
  { name: "S Mc.", email: "sMc@email.com", phone: "5-6421", title: "Executive Assistant (A)", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Tim Mc.", email: "timMc@email.com", phone: "(416) 325-6616", title: "Financial and Branch Coordinator (A)", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Al Sc.", email: "als@email.com", phone: "2-3961", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Ke Cle.", email: "kc@email.com", phone: "(647) 973-9598", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Mar C.", email: "mc@email.com", phone: "5-7602", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "M Ch.", email: "mch@email.com", phone: "5-6642", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Ni Bha.", email: "nb@email.com", phone: "5-6646", title: "Jr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Ram K.", email: "rk@email.com", phone: "(416) 325-8914", title: "Jr. Business Planning Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Yan Ad.", email: "yad@email.com", phone: "(416) 325-6573", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Am L.", email: "a.l@email.com", phone: "5-6643", title: "Manager (A)", business_planning_and_finance: true, manager: true, password: "123456" },
  { name: "Jo Y.", email: "joy12@email.com", phone: "2-3418", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Bill C.", email: "bc@email.com", phone: "5-6783", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Kat S.", email: "ks@email.com", phone: "(437) 992-5272", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Tai An.", email: "tai.an@email.com", phone: "5-4285", title: "Manager (A)", business_planning_and_finance: true, manager: true, password: "123456" },
  { name: "Ja L.", email: "jl@email.com", phone: "2-3299", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Pat Go.", email: "pgo@email.com", phone: "416-212-9207", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Se Z.", email: "sez@email.com", phone: "(416) 212-3299", title: "Jr. Financial Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Sh D.", email: "shd@email.com", phone: "5-6573", title: "Financial Analyst (A)", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Aso S.", email: "as@email.com", phone: "5-6425", title: "Controller", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Su Che.", email: "sche@email.com", phone: "(416) 212-1473", title: "Team Lead, Controllership", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Dave C.", email: "dav.c@email.com", phone: "4-4122", title: "Financial Analyst ad Accounting Lead", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Dor Ch", email: "ch.d@email.com", phone: "5-4767", title: "Sr. Financial Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "G C.", email: "gc@email.com", phone: "5-6465", title: "Sr. Accountant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Kam Si.", email: "ksi@email.com", phone: "5-9881", title: "Sr. Accountant", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Oxana V.", email: "ox.v@email.com", phone: "5-6821", title: "Financial Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Ren Na.", email: "rn@email.com", phone: "5-6426", title: "Junior Financial Analyst (A)", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Jo K.", email: "jk@email.com", phone: "(416) 327-3866", title: "Manager", business_planning_and_finance: true, manager: true, password: "123456" },
  { name: "Jen H.", email: "jh@email.com", phone: "(416) 325-6952", title: "Sr. Project Lead", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Nel Pa.", email: "np@email.com", phone: "(416) 212-3551", title: "Sr. Project Lead", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Lu P.", email: "lup@email.com", phone: "6-7360", title: "Business Analyst", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Cam Ma.", email: "ca.m@email.com", phone: "(416) 327-0823", title: "Sr. Project Lead", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Gin Go", email: "gg@email.com", phone: "(416) 212-8761", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Jev Je.", email: "jj@email.com", phone: "(416) 327-0572", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Sher Lo.", email: "slo@email.com", phone: "(416) 325-6991", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "S. B. N.", email: "sbn@email.com", phone: "(416) 325-2987", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "123456" },
  { name: "Tahm No.", email: "ta.n@email.com", phone: "(416) 212-0727", title: "Jr. Advisor", business_planning_and_finance: true, staff: true, password: "123456" }])

  Opportunity.create([{ name: "Diversity Career Champions Program (DCCP)", description: "Program" },
    { name: 'Emerging Leaders Management Program (ELMP)', description: "The ELMP provides a framework for understanding leadership essentials, refining individual leadership style and developing capability in the six areas of the OPS Leader-Manager Model. The program incorporates theory-based learning, practical training, and a strategic thinking workshop to support individual contributors in becoming better prepared to advance into a management role." },
    { name: 'Advancing into Management (AIM)', description: "Program" },
    { name: 'Senior Leadership Potential Assessment (SLPA)', description: "Program" },
    { name: 'Leadership Development Program (LDP)', description: "Rack up your acquaintences here!" },
    { name: 'Leadership 2.0', description: "Program" },
    { name: 'Job Interview Skills Program', description: "Training Session" },
    { name: 'Résumé Writing Skills Course', description: "Training Session" },
    { name: 'WEAR Form Re-Fresher', description: "Training Session" },
    { name: 'Student Orientation & Onboarding', description: "Training Session" },
    { name: 'Advancing into Management (AIM)', description: "Training Session" }])
