User.create([{ name: "Robert B.", email: "robb@email.com", phone: "(416) 222-2222", title: "Assistant Deputy Minister", adm_office: true, adm: true, password: "816260" },
  { name: 'Judith P.', email: "jp@email.com", phone: "(416) 333-333", title: "Executive Assistant", adm_office: true, staff: true, password: "598482" },
  { name: "Connie C.", email: "cc@email.com", phone: "(416) 111-1111", title: "Admin. Coordinator", adm_office: true, staff: true, password: "621106" },
  { name: "Natasha R.", email: "natr@email.com", phone: "(416) 111-1111", title: "Issues & Communications Coordinator", adm_office: true, staff: true, password: "826484" },
  { name: "Colleen Desjardins", email: "cg@email.com", phone: "(416) 111-1111", title: "Office Manager", adm_office: true, staff: true, password: "416600" },
  { name: "Allyne Sareno", email: "aly@email.com", phone: "(416) 111-1111", title: "Sr. Communications Advisor", adm_office: true, staff: true, password: "618349" },
  # { name: "Isolina K.", email: "isku@email.com", phone: "(416) 325-9366", title: "Exec. Lead, Transfer Payment Information", adm_office: true, staff: true, password: "808693" },
  # HR
  { name: "Christina C.", email: "chrc@email.com", phone: "(416) 111-1111", title: "Director", strategic_human_resources: true, director: true, password: "799127" },
  { name: "Michele J.", email: "michj@email.com", phone: "(416) 222-2222", title: "Admin. Assistant", strategic_human_resources: true, staff: true, password: "154113" },
  { name: "Annette A.", email: "anna@email.com", phone: "(416) 111-1111", title: "Manager", strategic_human_resources: true, manager: true, password: "558731" },
  { name: "Nav N.", email: "nn@email.com", phone: "(416) 111-1111", title: "Manager", strategic_human_resources: true, manager: true, password: "724656" },
  { name: "Jamie", email: "jam@email.com", phone: "(416) 111-1111", title: "Manager", strategic_human_resources: true, manager: true, password: "596182" },
  { name: "Ellen C.", email: "ellc@email.com", phone: "(416) 333-333", title: "Strategic Business Advisor", strategic_human_resources: true, staff: true, password: "381674" },
  { name: "Vanja P.", email: "vp@email.com", phone: "(416) 333-333", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "460729" },
  { name: "Rachel F.", email: "rf@email.com", phone: "(416) 333-333", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "360863" },
  { name: "Jill D.", email: "jd@email.com", phone: "(416) 222-2222", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "499398" },
  { name: "Gabrielle C.", email: "gbc@email.com", phone: "(416) 111-1111", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "871970" },
  { name: "Nadeem A.", email: "nad.a@email.com", phone: "(416) 222-2222", title: "Project Coordinator", strategic_human_resources: true, staff: true, password: "178041" },
  { name: "Daniel C.", email: "dchee@email.com", phone: "(416) 222-2222", title: "Systems Officer", strategic_human_resources: true, staff: true, password: "dosomework" },
  # { name: "Andrew H.", email: "anh@email.com", phone: "(416) 111-1111", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "059316" },
  { name: "Yvonne C.", email: "yc@email.com", phone: "(416) 111-1111", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "680748" },
  { name: "Dianne B.", email: "db@email.com", phone: "(416) 333-333", title: "Workforce Planner", strategic_human_resources: true, staff: true, password: "300229" },
  { name: "Sean D.", email: "sd@email.com", phone: "(416) 222-2222", title: "HR Project Advisor", strategic_human_resources: true, staff: true, password: "280225" },
  { name: "Xander N.", email: "xn@email.com", phone: "(416) 111-1111", title: "HR Business Advisor", strategic_human_resources: true, staff: true, password: "143537" },
  #SMF
  { name: "Nelson J.", email: "nj@email.com", phone: "(416) 111-1111", title: "Director", service_management_and_facilities: true, director: true, password: "545357" },
  { name: "Sureka D.", email: "srd@email.com", phone: "(416) 111-1111", title: "Financial and Admin. Coordinator", service_management_and_facilities: true, staff: true, password: "877241" },
  { name: "Peter R.", email: "pre@email.com", phone: "(416) 222-2222", title: "Coor Emerg Mgt Cont Plan", service_management_and_facilities: true, manager: true, password: "596049" },
  { name: "Jose L.", email: "jol@email.com", phone: "(416) 111-1111", title: "Business Analyst", service_management_and_facilities: true, staff: true, password: "172922" },
  { name: "Gillian C.", email: "gico@email.com", phone: "(416) 111-1111", title: "Emergency Management Assistant", service_management_and_facilities: true, staff: true, password: "191526" },
  { name: "Alma B.", email: "alb@email.com", phone: "(416) 333-333", title: "Manager", service_management_and_facilities: true, manager: true, password: "717259" },
  { name: "Patricia C.", email: "pac@email.com", phone: "(416) 222-2222", title: "Tougas FOI Coordinator", service_management_and_facilities: true, staff: true, password: "617573" },
  { name: "Dalia B.", email: "db@email.com", phone: "(416) 111-1111", title: "FOI Coordinator", service_management_and_facilities: true, staff: true, password: "798640" },
  { name: "Mimi N.", email: "min@email.com", phone: "(416) 333-333", title: "Coordinator", service_management_and_facilities: true, staff: true, password: "253630" },
  { name: "Elaine M.", email: "elm@email.com", phone: "(416) 333-333", title: "Info Officer", service_management_and_facilities: true, staff: true, password: "987438" },
  { name: "Pamela E.", email: "pe@email.com", phone: "(416) 111-1111", title: "IM and Access Strat Advisor", service_management_and_facilities: true, staff: true, password: "400399" },
  { name: "Jason T.", email: "jt@email.com", phone: "(416) 222-2222", title: "FOI Program Assistant", service_management_and_facilities: true, staff: true, password: "556976" },
  { name: "Christine P.", email: "cp@email.com", phone: "(416) 111-1111", title: "Manager", service_management_and_facilities: true, manager: true, password: "398073" },
  { name: "Mirjana Z.", email: "mz@email.com", phone: "(416) 111-1111", title: "General Admin", service_management_and_facilities: true, staff: true, password: "600233" },
  { name: "Lidia L.", email: "ll@email.com", phone: "(416) 333-333", title: "Facilities Coordinator/ Business Analyst", service_management_and_facilities: true, staff: true, password: "899317" },
  { name: "Maria A.", email: "ma@email.com", phone: "(416) 111-1111", title: "Security Coordinator", service_management_and_facilities: true, staff: true, password: "243097" },
  { name: "Robert C.", email: "rc@email.com", phone: "(416) 222-2222", title: "Facilities Mgmt Coordinator", service_management_and_facilities: true, staff: true, password: "501548" },
  { name: "Elizabeth T.", email: "elt@email.com", phone: "(416) 111-1111", title: "Manager, AIS Mkt & Comms", service_management_and_facilities: true, staff: true, password: "349017" },
  { name: "Sue S.", email: "ss@email.com", phone: "(416) 111-1111", title: "Project Manager", service_management_and_facilities: true, staff: true, password: "588308" },
  { name: "Beatriz V.", email: "bv@email.com", phone: "(416) 333-333", title: "Manager", service_management_and_facilities: true, manager: true, password: "550207" },
  { name: "Michael N.", email: "miken.@email.com", phone: "(416) 222-2222", title: "Information Services Officer", service_management_and_facilities: true, staff: true, password: "632316" },
  { name: "Casey C.", email: "caco@email.com", phone: "(416) 111-1111", title: "Client Relations Assistant", service_management_and_facilities: true, staff: true, password: "287741" },
  { name: "Amber B.", email: "amb@email.com", phone: "(416) 111-1111", title: "Client Relations Assistant", service_management_and_facilities: true, staff: true, password: "486237" },
  { name: "Rajaa R.", email: "rr@email.com", phone: "(416) 222-2222", title: "Client Relations Rep", service_management_and_facilities: true, staff: true, password: "300329" },
  { name: "Jonathan N.", email: "jon@email.com", phone: "(416) 222-2222", title: "Info Services Officer", service_management_and_facilities: true, staff: true, password: "395114" },
  { name: "Martin D.", email: "mde@email.com", phone: "(416) 222-2222", title: "Jr Prg Advisor", service_management_and_facilities: true, staff: true, password: "241726" },
  { name: "Lidya L.", email: "lls@email.com", phone: "(416) 222-2222", title: "Business Analyst", service_management_and_facilities: true, staff: true, password: "629457" },
  { name: "Shivaharan T.", email: "st@email.com", phone: "(416) 222-2222", title: "Business Analyst", service_management_and_facilities: true, staff: true, password: "172296" },
  { name: "S. D.", email: "sdi@email.com", phone: "(416) 222-2222", title: "Project Coordinator", service_management_and_facilities: true, staff: true, password: "294106" },
  { name: "Daniel B.", email: "dab@email.com", phone: "(416) 222-2222", title: "Project Manager", service_management_and_facilities: true, staff: true, password: "914375" },
  #BPF
  { name: "Kathryn R.", email: "ktr@email.com", phone: "(416) 222-2222", title: "Director", business_planning_and_finance: true, director: true, password: "280063" },
  { name: "Janica A.", email: "jaa@email.com", phone: "(416) 111-1111", title: "Project Management Lead", business_planning_and_finance: true, manager: true, password: "814511" },
  { name: "Sarah M.", email: "sMc@email.com", phone: "(416) 111-1111", title: "Executive Assistant", business_planning_and_finance: true, staff: true, password: "792680" },
  { name: "Timothy M.", email: "timMc@email.com", phone: "(416) 111-1111", title: "Financial and Branch Coordinator", business_planning_and_finance: true, staff: true, password: "307188" },
  { name: "Alexei S.", email: "als@email.com", phone: "(416) 222-2222", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "550247" },
  { name: "Kyle C.", email: "kc@email.com", phone: "(416) 111-1111", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "837092" },
  { name: "Martin C.", email: "mc@email.com", phone: "(416) 111-1111", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "709369" },
  { name: "Muneeb C.", email: "mch@email.com", phone: "(416) 111-1111", title: "Team Lead", business_planning_and_finance: true, staff: true, password: "421553" },
  { name: "Nisarg B.", email: "nb@email.com", phone: "(416) 222-2222", title: "Jr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "246019" },
  { name: "Raman K.", email: "rk@email.com", phone: "(416) 111-1111", title: "Jr. Business Planning Analyst", business_planning_and_finance: true, staff: true, password: "559088" },
  { name: "Yasmin A.", email: "yad@email.com", phone: "(416) 222-2222", title: "Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "694824" },
  { name: "Amanda L.", email: "aml@email.com", phone: "(416) 111-1111", title: "Manager (A)", business_planning_and_finance: true, manager: true, password: "168882" },
  { name: "Jose Y.", email: "joy12@email.com", phone: "(416) 111-1111", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "851857" },
  { name: "Bill C.", email: "bc@email.com", phone: "(416) 333-333", title: "Sr. Business Planning Consultant", business_planning_and_finance: true, staff: true, password: "402483" },
  { name: "Katarina S.", email: "ks@email.com", phone: "(416) 333-333", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "286402" },
  { name: "Pratima G.", email: "pgo@email.com", phone: "(416) 111-1111", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "125317" },
  { name: "Sean Z.", email: "sez@email.com", phone: "(416) 111-1111", title: "Jr. Financial Analyst", business_planning_and_finance: true, staff: true, password: "352953" },
  { name: "Shalini D.", email: "shd@email.com", phone: "(416) 111-1111", title: "Business Practice Analyst", business_planning_and_finance: true, staff: true, password: "115648" },
  { name: "Asokan S.", email: "as@email.com", phone: "(416) 222-2222", title: "Controller", business_planning_and_finance: true, staff: true, password: "758474" },
  { name: "Sudheendran C.", email: "sche@email.com", phone: "(416) 222-2222", title: "Team Lead", business_planning_and_finance: true, staff: true, password: "455191" },
  { name: "David C.", email: "davc@email.com", phone: "(416) 222-2222", title: "Accounting Lead", business_planning_and_finance: true, staff: true, password: "580235" },
  { name: "Dorothy C.", email: "chd@email.com", phone: "(416) 222-2222", title: "Sr. Controllership Consultant", business_planning_and_finance: true, staff: true, password: "378240" },
  { name: "Grace C.", email: "gc@email.com", phone: "(416) 222-2222", title: "Sr. Accountant", business_planning_and_finance: true, staff: true, password: "818451" },
  { name: "Kamala S.", email: "ksi@email.com", phone: "(416) 111-1111", title: "Sr. Accountant", business_planning_and_finance: true, staff: true, password: "471520" },
  { name: "Oxana V.", email: "ox.v@email.com", phone: "(416) 111-1111", title: "Financial Officer", business_planning_and_finance: true, staff: true, password: "879994" },
  { name: "Renuga N.", email: "rn@email.com", phone: "(416) 111-1111", title: "Junior Financial Analyst (A)", business_planning_and_finance: true, staff: true, password: "607193" },
  { name: "Jennifer H.", email: "jh@email.com", phone: "(416) 111-1111", title: "Sr. Project Lead", business_planning_and_finance: true, staff: true, password: "151457" },
  { name: "Andrea W.", email: "aw@email.com", phone: "(416) 111-1111", title: "Manager", business_planning_and_finance: true, manager: true, password: "183178" },
  { name: "Camille M.", email: "ca.m@email.com", phone: "(416) 111-1111", title: "Divisional Coordinator", business_planning_and_finance: true, staff: true, password: "818505" },
  { name: "Gina G.", email: "gg@email.com", phone: "(416) 333-333", title: "Divisional Coordinator", business_planning_and_finance: true, staff: true, password: "307951" },
  { name: "Jeevithan J.", email: "jj@email.com", phone: "(416) 333-333", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "484325" },
  { name: "Sherma L.", email: "slo@email.com", phone: "(416) 333-333", title: "Corporate Coordinator", business_planning_and_finance: true, staff: true, password: "637613" },
  { name: "Sarah N.", email: "sbn@email.com", phone: "(416) 333-333", title: "Divisional Coordinator", business_planning_and_finance: true, staff: true, password: "514484" },
  { name: "Tahmina N.", email: "ta.n@email.com", phone: "(416) 111-1111", title: "Jr. Advisor", business_planning_and_finance: true, staff: true, password: "964487" },
  { name: "Rosanna M.", email: "rosm@email.com", phone: "(416) 111-1111", title: "Bus Planning Consult", business_planning_and_finance: true, staff: true, password: "546274" },
  { name: "Nisarg B.", email: "nib@email.com", phone: "(416) 111-1111", title: "Bus Planning Consult", business_planning_and_finance: true, staff: true, password: "964487" },
  { name: "Kritika K.", email: "krit@email.com", phone: "(416) 111-1111", title: "Jr. Bus Planning Analyst", business_planning_and_finance: true, staff: true, password: "624417" },
  { name: "Y. Z.", email: "yz@email.com", phone: "(416) 111-1111", title: "Sr. Accountant", business_planning_and_finance: true, staff: true, password: "768147" }])
# Energy
  # { name: "Luxman P.", email: "lup@email.com", phone: "(416) 111-1111", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "286670" },
  # { name: "Tai A.", email: "tai@email.com", phone: "(416) 111-1111", title: "Manager (A)", business_planning_and_finance: true, manager: true, password: "493678" },
  # { name: "Janet L.", email: "jl@email.com", phone: "(416) 222-2222", title: "Sr. Business Analyst", business_planning_and_finance: true, staff: true, password: "736686" },
  Opportunity.create([{ name: "Diversity Career Champions Program" },
    { name: 'Emerging Leaders Management Program' },
    { name: 'Advancing into Management' },
    { name: 'Senior Leadership Potential Assessment' },
    { name: 'Leadership Development Program' },
    { name: 'Leadership 2.0' },
    { name: 'Co-op Student Onboarding Lunch' },
    { name: 'CSD Community Outreach' },
    { name: 'Lunch & Learn: Nuclear Emergency Management' },
    { name: 'Lunch & Learn: Emergency & Personal Preparedness' },
    { name: 'Lunch & Learn: Research, Science & Strategy Division' },
    { name: 'Lunch & Learn: Commercialization & Scale-Ups Division' },
    { name: 'Lunch & Learn: Behavioral Insights' },
    { name: 'Lunch & Learn: Business Climate & Funding Administration Division' },
    { name: 'Lunch & Learn: Strategic Programs Development & Delivery Office' },
    { name: 'Lunch & Learn: Ontario Investment Office' }])
